### PR TITLE
Fix z-index bug by adding a wrapper

### LINKED ISSUE #25288: [Bug]: Onboarding broken in SB8
### Describe the bug

The onboarding addon fails to render properly and blocks user interaction. Probably due to some React version mismatch -- 8.0 manager UI is based on React18, 7.x is React16. Probably just need to create a `next` branch of the addon & externalize React on it? Or just bump a major?

**NOTE: This isn't an issue in 7.x.**

image

### To Reproduce

In an empty directory:

```
npx storybook@next init
```

Then choose react-vite.

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ndelangen**
Closes: https://github.com/storybookjs/storybook/issues/25288

Tested locally using the canary:
Screenshot 2024-01-23 at 14 18 45
Screenshot 2024-01-23 at 14 19 39

<details>
  <summary>📦 Published PR as canary version: <code>1.0.11-canary.82.870db45.0</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @storybook/addon-onboarding@1.0.11-canary.82.870db45.0
  # or 
  yarn add @storybook/addon-onboarding@1.0.11-canary.82.870db45.0
  ```
</details>

### CODE REVIEW

File: src/features/WelcomeModal/WelcomeModal.tsx [hunk 1]
```diff
@@ -26,31 +26,33 @@ export const WelcomeModal: FC<WelcomeModalProps> = ({
...
-          </SkipButton>
-          <Background>
-            <Circle1 />
-            <Circle2 />
-            <Circle3 />
-          </Background>
-        </ModalContentWrapper>
-      )}
-    </Modal>
+    <div style={{ zIndex: 10 }}>
```
Comment (yannbf) [inline src/features/WelcomeModal/WelcomeModal.tsx:29]: It would have been better if the style was passed to the Modal element, can you try that instead?
